title: Juan Soler
description: Probando paginas estaticas con jekyll
author: Juan Soler
logo: /static/img/avatar.png
github: https://github.com/juansoler
about: Estudiante de Ingenieria Informática

baseurl: ""
url: "http://juansoler.github.com/juansoler"

disqus_shortname: juansoler
google_analytics:  

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
